# Generated by Django 4.2.5 on 2023-10-02 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('89dd0e78-bcb8-499d-b72c-e78dd4b9bfa0'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=250)),
                ('description', models.TextField()),
                ('demo_link', models.CharField(max_length=250)),
                ('source_code', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
