# Generated by Django 4.2.5 on 2023-10-02 09:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('31b00705-f76b-445b-a558-fe8dfe912698'), primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76746b90-f0d9-4167-a4e9-10a5aab52edf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('98c15b78-e5aa-4032-b986-1e488eb71a41'), primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=250)),
                ('values', models.CharField(choices=[{'up', 'up vote'}, {'down', 'down vote'}], max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app1.tags'),
        ),
    ]
