# Generated by Django 4.2.5 on 2023-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_project_id_alter_review_id_alter_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='values',
            field=models.CharField(choices=[('up', 'up vote'), ('down', 'down vote')], max_length=200),
        ),
    ]
